# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import  numpy  as  np 
import  matplotlib.pyplot  as  plt 
from  scipy  import  *

#### 2. Print the numpy version and the configuration (★☆☆)

In [15]:
print(np.__version__)
print(np.show_config())

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) 

#### 3. Create a null vector of size 10 (★☆☆)

In [14]:
x3 = np.zeros(10)
print(x3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [13]:
x4 = np.array([[31323, 210, 34],
              [3030, 43300, 6003]])
print("Memory size of one array element in bytes: ",
      x4.itemsize)

Memory size of one array element in bytes:  4


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
x6=np.zeros(10)
x6[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
x7 = np.arange(10,50)
print(x7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
x8 = np.arange(10,50)
print(np.flip(x8))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
x9 =  np.arange(0, 9).reshape(3,3)
print(x9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [23]:
x10 = np.array([1,2,0,0,4,0])
print(np.nonzero(x10))


(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
x10=np.identity(3)
print('3x3 matrix:')
print(x10)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
x12 = np.random.random((3,3,3))
print(x12)

[[[0.25801421 0.89707643 0.27282957]
  [0.9111605  0.67162995 0.52773058]
  [0.18494343 0.79645097 0.70131131]]

 [[0.74367376 0.41322834 0.36655861]
  [0.20740273 0.56624597 0.82335509]
  [0.86678598 0.0291285  0.67490426]]

 [[0.01856311 0.58631318 0.67165087]
  [0.3607973  0.50279248 0.39229868]
  [0.34298263 0.60214534 0.50562903]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
x13 = np.random.random((10,10))
xmin, xmax = x13.min(), x13.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Minimum and Maximum Values:
0.0021490577511427134 0.9877891790163712


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
x14 = np.random.random(30)
print(np.mean(x14))

0.4462161872899112


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [31]:
x15 = np.ones((5,5))
print("Original array:")
print(x15)
print("1 on the border and 0 inside in the array")
x15[1:-1,1:-1] = 0
print(x15)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [35]:
x16 = np.ones((2,2))
print("Original array:")
print(x16)
print("0 on the border and 1 inside in the array")
x16 = np.pad(x16, pad_width=1, mode='constant', constant_values=0)
print(x16)

Original array:
[[1. 1.]
 [1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [41]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [42]:
x18 = np.diag([1, 2, 3, 4, 5])
print(x18)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [43]:
x19 = np.ones((3,3))
print("Checkerboard pattern:")
x19 = np.zeros((8,8),dtype=int)
x19[1::2,::2] = 1
x19[::2,1::2] = 1
print(x19)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [44]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [45]:
x21 = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(x21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [46]:
x22 = np.random.random((5,5))
x22 = (x22 - np.mean (x22)) / (np.std (x22))
print(x22)

[[-0.46845007  0.13456141  1.42028777  0.71395743  0.79236195]
 [-0.9980221   1.188192    0.73143606  0.5501125  -0.65527092]
 [ 0.63509538 -0.23454166  0.37169103  0.65173745  1.37296909]
 [ 1.71327586 -1.56738256 -0.94482393  0.81879344 -1.14331557]
 [-1.47441542 -1.7472877  -0.94867983 -0.78868089 -0.12360071]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [48]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [51]:
x24 = np.dot(np.ones((5,3)), np.ones((3,2)))
print(x24)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [52]:
x25 = np.arange(11)
x25[(3 < x25) & (x25 < 8)] *= -1
print(x25)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [53]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [64]:
#no_one

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [65]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\_Pala4inta_\AppData\Local\Temp\ipykernel_18780\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\_Pala4inta_\AppData\Local\Temp\ipykernel_18780\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [67]:
x29 = np.random.uniform(-10,+10,10)
print(np.where(x29>0, np.ceil(x29), np.floor(x29)))

[10. -4.  7.  6. -7. -8.  4.  8.  5.  7.]


In [68]:
x30 = np.random.randint(0,10,10)
y30 = np.random.randint(0,10,10)
print(np.intersect1d(x30,y30))

[5 6 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [69]:
defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [70]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [73]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2022-10-29 2022-10-30 2022-10-31


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [74]:
x34 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x34)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [75]:
x35 = np.ones(3)*1
y35 = np.ones(3)*2
np.add(x35,y35,out=y35)
np.divide(x35,2,out=x35)
np.negative(x35,out=x35)
np.multiply(x35,y35,out=x35)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [76]:
x36 = np.random.uniform(0,10,10)

print(x36 - x36%1)
print(x36 // 1)
print(np.floor(x36))
print(x36.astype(int))
print(np.trunc(x36))

[2. 5. 4. 8. 8. 4. 3. 5. 1. 6.]
[2. 5. 4. 8. 8. 4. 3. 5. 1. 6.]
[2. 5. 4. 8. 8. 4. 3. 5. 1. 6.]
[2 5 4 8 8 4 3 5 1 6]
[2. 5. 4. 8. 8. 4. 3. 5. 1. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [77]:
x37 = np.zeros((5,5))
x37 += np.arange(5)
print(x37)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [79]:
def generate():
    for x in range(10):
        yield x
x38 = np.fromiter(generate(),dtype=float,count=-1)
print(x38)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [80]:
x39 = np.linspace(0,1,11,endpoint=False)[1:]
print(x39)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [81]:
x40 = np.random.random(10)
x40.sort()
print(x40)

[0.01317551 0.10803257 0.13105095 0.17111068 0.60329713 0.64012543
 0.64346542 0.73416941 0.74430064 0.81087702]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [82]:
x41 = np.arange(10)
np.add.reduce(x41)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [83]:
x42 = np.random.randint(0,2,5)
y42 = np.random.randint(0,2,5)

equal = np.allclose(x42,y42)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [86]:
x43 = np.zeros(10)
x43.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [87]:
x43 = np.random.random((10,2))
X,Y = x43[:,0], x43[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.8002149  1.23148031 1.36265263 0.47598092 0.2622045  0.61621606
 0.58320149 0.5168151  0.98893536 0.60347095]
[0.16744003 0.91033642 0.74903889 1.51131977 0.26034525 0.34680292
 0.6645716  1.53420581 1.46722008 0.78518584]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [88]:
x25 = np.random.random(10)
x25[x25.argmax()] = 0
print(x25)

[0.13761808 0.28199797 0.53008182 0.80677033 0.3859291  0.17533983
 0.57275063 0.         0.44075706 0.57322823]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [90]:
x46 = np.zeros((5,5), [('x',float),('y',float)])
x46['x'], x46['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(x46)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [91]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [92]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [93]:
np.set_printoptions(threshold=float("inf"))
x49 = np.zeros((40,40))
print(x49)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [94]:
x50 = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(x50-v)).argmin()
print(x50[index])

73


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [95]:
x51 = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(x51)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\_Pala4inta_\AppData\Local\Temp\ipykernel_18780\1089870041.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x51 = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [96]:
x52 = np.random.random((10,2))
X,Y = np.atleast_2d(x52[:,0], x52[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.27585878 0.68876592 0.3245059  0.26593105 0.43957562
  0.22512098 0.15618925 0.62241008 0.41941906]
 [0.27585878 0.         0.63128927 0.45954799 0.45752436 0.40688033
  0.47019447 0.43116213 0.50127352 0.31223177]
 [0.68876592 0.63128927 0.         1.00670066 0.55115982 1.03229362
  0.89677818 0.74690093 0.17910295 0.31911933]
 [0.3245059  0.45954799 1.00670066 0.         0.56370107 0.25411959
  0.20922262 0.35534959 0.92053208 0.71502044]
 [0.26593105 0.45752436 0.55115982 0.56370107 0.         0.70550633
  0.3913525  0.22370754 0.55662084 0.39984284]
 [0.43957562 0.40688033 1.03229362 0.25411959 0.70550633 0.
  0.43794732 0.54069724 0.90815365 0.71544243]
 [0.22512098 0.47019447 0.89677818 0.20922262 0.3913525  0.43794732
  0.         0.1680376  0.84435922 0.64328353]
 [0.15618925 0.43116213 0.74690093 0.35534959 0.22370754 0.54069724
  0.1680376  0.         0.71453499 0.52350381]
 [0.62241008 0.50127352 0.17910295 0.92053208 0.55662084 0.90815365
  0.84435922 0.71453

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [97]:
x53 = (np.random.rand(10)*100).astype(np.float32)
Y = x53.view(np.int32)
Y[:] =x53
print(Y)

[85 39 26 72 47 16 64 71 36  0]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [99]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\_Pala4inta_\AppData\Local\Temp\ipykernel_18780\4147279938.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [101]:
x55 = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x55):
    print(index, value)
for index in np.ndindex(x55.shape):
    print(index, x55[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [102]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [103]:
n = 10
p = 3
x57 = np.zeros((n,n))
np.put(x57, np.random.choice(range(n*n), p, replace=False),1)
print(x57)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [104]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.14251805 -0.21407418 -0.04289674 -0.13100937 -0.04143406  0.45413888
  -0.25181771  0.28949947  0.16760537 -0.08749361]
 [-0.28119792  0.15319761  0.41495673 -0.19500119  0.24139202 -0.22297974
   0.25518434  0.02464319  0.12465393 -0.51484898]
 [-0.41132672 -0.35556561 -0.0306245   0.22737772  0.15485516 -0.41156447
   0.02896171  0.35564207  0.52753809 -0.08529345]
 [ 0.18373545  0.06733573 -0.23724472 -0.07194269 -0.32855467  0.19478537
  -0.22484492  0.06601403  0.01432022  0.3363962 ]
 [ 0.42802455  0.48393292 -0.1497216   0.05183523 -0.41476052  0.08026439
  -0.06316679  0.02374576 -0.03112511 -0.40902883]]


#### 59. How to sort an array by the nth column? (★★☆)

In [105]:
x59 = np.random.randint(0,10,(3,3))
print(x59)
print(x59[x59[:,1].argsort()])

[[5 2 7]
 [6 3 8]
 [5 9 1]]
[[5 2 7]
 [6 3 8]
 [5 9 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [110]:
x60 = np.random.randint(0,3,(3,10))
print((~x60.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [111]:
x61 = np.random.uniform(0,1,10)
y = 0.5
m = x61.flat[np.abs(x61 - y).argmin()]
print(m)

0.5065163651113003


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [112]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [113]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

x63 = NamedArray(np.arange(10), "range_10")
print (x63.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [116]:
x64 = np.ones(10)
I = np.random.randint(0,len(x64),20)
x64 += np.bincount(I, minlength=len(x64))
print(x64)

[3. 6. 3. 1. 1. 6. 2. 4. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [117]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [118]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [119]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[60 39 53 59]
 [69 40 62 47]
 [54 43 48 58]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [120]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.65170525 0.61703176 0.21014993 0.60126319 0.48379436 0.42036811
 0.31789297 0.49430203 0.40126797 0.52917272]


#### 69. How to get the diagonal of a dot product? (★★★)

In [121]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([0.29236246, 1.29733102, 1.35143357, 1.55172541, 0.75899194])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [122]:
X = np.array([1,2,3,4,5])
nz = 3
X0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
X0[::nz+1] = Z
print(X0)

[3. 0. 0. 0. 2. 0. 0. 0. 4. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0.
 2. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [123]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [124]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [125]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 45) ( 3, 85) ( 7, 57) ( 7, 75) (12, 38) (12, 64) (14, 24) (14, 88)
 (19, 57) (19, 65) (23, 56) (23, 74) (24, 88) (28, 84) (28, 94) (32, 61)
 (32, 94) (38, 64) (45, 85) (50, 72) (50, 89) (52, 76) (52, 81) (56, 74)
 (57, 65) (57, 75) (61, 94) (72, 89) (76, 81) (84, 94)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [126]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [127]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
x75 = np.arange(20)
print(moving_average(x75, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [128]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
x76 = rolling(np.arange(10), 3)
print(x76)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [130]:
x77 = np.random.randint(0,2,100)
np.logical_not(x77 , out=x77 )

x77 = np.random.uniform(-1.0,1.0,100)
np.negative(x77 , out=x77 )

array([-0.69748397, -0.16252598, -0.24592327, -0.69349837,  0.50708778,
        0.29868298, -0.21910526, -0.00242679,  0.9524877 , -0.02674788,
       -0.02818294, -0.15750511,  0.0291562 ,  0.59441729, -0.57621683,
       -0.53714239, -0.92239361, -0.54724727,  0.6316731 ,  0.56894057,
        0.93097354,  0.83096403,  0.52769466,  0.78773024, -0.11545442,
        0.10619484, -0.57141191, -0.95030089,  0.75878865,  0.3451978 ,
        0.50968773, -0.57332509, -0.90855911,  0.46198382,  0.29475553,
       -0.86479774,  0.51430028, -0.37767331, -0.41228482,  0.00912452,
        0.43246321, -0.40155666,  0.73691409,  0.62367673, -0.4007617 ,
        0.52085322,  0.69120412,  0.96046538,  0.31043185,  0.85962807,
        0.28084254,  0.20625777,  0.13652667,  0.88246172,  0.36577791,
        0.45820759,  0.82132585,  0.4811657 ,  0.65995986,  0.62439004,
       -0.36347295, -0.61881319,  0.61814982, -0.22418919, -0.46534213,
        0.51797033, -0.6056294 , -0.70969111, -0.7294144 ,  0.63

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [131]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 9.7338077   1.32480844  4.28438163  0.64475109  4.82354266 11.13210247
 11.24380539  0.23958791  1.48735775  6.34566333]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [132]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.13672761 11.83604959  3.15423955  1.72983433  2.70906921  0.71479681
   4.78290501  8.33195884 10.05445447  1.33676546]
 [15.69997606 13.11083731  2.69379401 12.14143835 13.51620652 10.11691113
  12.85336576  3.91792395  4.47536144  5.02392224]
 [ 6.04278244 12.93774066  4.57237934  1.35346824  2.09693485  1.58425682
   5.02502362  9.73500592 11.47214542  2.75231599]
 [20.52404569 15.70006271  3.26707661 16.91470918 18.08397497 14.24803041
  17.48579714  4.06624862  4.04157341  5.86912632]
 [11.63945274  6.22841998  7.95462151  9.28057357 11.80707642  9.86045072
   7.59754717  1.94605081  0.91213856 10.02368152]
 [ 5.64080272 12.04774352  3.7967571   1.12157929  2.02248876  1.46674888
   4.44452494  8.89986223 10.68357227  2.00396672]
 [10.22239773  1.51952245 12.60795747  8.84969348 12.25825995 11.35090055
   5.09787709  6.80779267  5.61422206 14.57012025]
 [20.53492416 15.60138515  3.396006   16.95118322 18.14173684 14.32892284
  17.46609532  3.93904083  3.91275287  5.99795362]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [136]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [137]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [138]:
x83 = np.random.randint(0,10,50)
print(np.bincount(x83).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [139]:
x84 = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (x84.shape[0]-3)
j = 1 + (x84.shape[1]-3)
C = stride_tricks.as_strided(x84, shape=(i, j, n, n), strides=x84.strides + x84.strides)
print(C)

[[[[4 1 0]
   [4 4 3]
   [3 0 0]]

  [[1 0 0]
   [4 3 1]
   [0 0 4]]

  [[0 0 2]
   [3 1 2]
   [0 4 3]]

  [[0 2 1]
   [1 2 0]
   [4 3 4]]

  [[2 1 0]
   [2 0 1]
   [3 4 3]]

  [[1 0 1]
   [0 1 0]
   [4 3 0]]

  [[0 1 3]
   [1 0 3]
   [3 0 2]]

  [[1 3 4]
   [0 3 4]
   [0 2 2]]]


 [[[4 4 3]
   [3 0 0]
   [1 3 0]]

  [[4 3 1]
   [0 0 4]
   [3 0 4]]

  [[3 1 2]
   [0 4 3]
   [0 4 0]]

  [[1 2 0]
   [4 3 4]
   [4 0 1]]

  [[2 0 1]
   [3 4 3]
   [0 1 2]]

  [[0 1 0]
   [4 3 0]
   [1 2 2]]

  [[1 0 3]
   [3 0 2]
   [2 2 1]]

  [[0 3 4]
   [0 2 2]
   [2 1 3]]]


 [[[3 0 0]
   [1 3 0]
   [2 1 0]]

  [[0 0 4]
   [3 0 4]
   [1 0 0]]

  [[0 4 3]
   [0 4 0]
   [0 0 2]]

  [[4 3 4]
   [4 0 1]
   [0 2 3]]

  [[3 4 3]
   [0 1 2]
   [2 3 0]]

  [[4 3 0]
   [1 2 2]
   [3 0 3]]

  [[3 0 2]
   [2 2 1]
   [0 3 2]]

  [[0 2 2]
   [2 1 3]
   [3 2 1]]]


 [[[1 3 0]
   [2 1 0]
   [1 4 0]]

  [[3 0 4]
   [1 0 0]
   [4 0 3]]

  [[0 4 0]
   [0 0 2]
   [0 3 2]]

  [[4 0 1]
   [0 2 3]
   [3 2 4]]

  [[0 1 2]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [140]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2  7 14  2 14]
 [ 7  0  7  3 13]
 [14  7  4 42 13]
 [ 2  3 42  0 10]
 [14 13 13 10  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [141]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [142]:

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [143]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0
  0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
  0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0
  0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [144]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [20]:

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    print(type(arrays))
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

<class 'list'>
[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [146]:
x91 = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(x91.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [147]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.64 s ± 27.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
389 ms ± 17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
226 ms ± 8.25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [148]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [149]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[2 0 1]
 [4 1 3]
 [3 4 2]
 [2 2 1]
 [1 4 0]
 [1 1 2]
 [1 1 4]
 [2 4 0]
 [1 2 4]
 [3 1 1]]
[[2 0 1]
 [4 1 3]
 [3 4 2]
 [2 2 1]
 [1 4 0]
 [1 1 2]
 [1 1 4]
 [2 4 0]
 [1 2 4]
 [3 1 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [150]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [151]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [152]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.25138149, 0.32062155, 0.09367149, 0.24496388, 0.31083014,
        0.29910767, 0.34037647, 0.18877939, 0.069084  , 0.2932083 ],
       [0.50600896, 0.64538316, 0.18855252, 0.49309088, 0.62567391,
        0.6020776 , 0.68514808, 0.37999642, 0.13906005, 0.59020269],
       [0.54360199, 0.69333074, 0.20256069, 0.52972418, 0.67215723,
        0.64680788, 0.73604993, 0.40822757, 0.14939127, 0.63405074],
       [0.20097662, 0.25633325, 0.07488928, 0.19584581, 0.24850514,
        0.23913316, 0.27212708, 0.15092696, 0.05523186, 0.23441668],
       [0.44062517, 0.56199018, 0.16418876, 0.4293763 , 0.54482765,
        0.52428033, 0.59661688, 0.3308953 , 0.12109145, 0.51393984],
       [0.55233314, 0.70446678, 0.20581415, 0.53823243, 0.68295319,
        0.65719668, 0.74787211, 0.41478438, 0.15179074, 0.64423465],
       [0.08336886, 0.10633183, 0.03106547, 0.0812405 , 0.10308458,
        0.0991969 , 0.1128834 , 0.06260732, 0.02291121, 0.09724042],
       [0.07909286, 0.10087805, 0.0294721

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [153]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [154]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [155]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23937556  0.15732338]
